[project]
name = "mava-api"
authors = [
  { name = "Stefan Milosavljevic", email = "stefan.milosavljevic@sdsc.ethz.ch" },
  { name = "Sabine Maennel", email = "sabine.maennel@sdsc.ethz.ch" },
]
description = "An ontology based API to allow video-annotation tools to communicate and exchange information."
readme = "README.md"
requires-python = ">=3.13"
version = "0.0.1"

dependencies = [
    "pydantic>=2.10.6",
]
[dependency-groups]
dev = [
    "notebook>=7.3.2",
]

[project.scripts]
cli = 'mava-api.cli:main'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
    ".direnv",
    ".devenv",
    ".output",
]

[tool.ruff]
extend-include = ["*.ipynb"]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
extend-select = [
    "W605",   # pycodestyle: invalid-escape-sequence
    "S102",   # flake8-bandit: exec-builtin
    "INP",    # flake8-no-pep420
    "PYI",    # flake8-pyi
    "PT",     # flake8-pytest-style
    "PGH",    # pygrep-hooks
    "PL",     # Pylint
    "NPY",    # NumPy-specific rules
    "RUF",    # Ruff-specific rules
]
ignore = [
    "NPY002", # numpy-legacy-random
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["INP001"]
"[!t][!e][!s][!t][!s]*/**" = ["PT"]
