name: SHACL validation

on:
  workflow_call:
  push:
    paths:
      - "src/ontology/**"
  pull_request:
    paths:
      - "src/ontology/**"
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: SHACL validation
        run: |
          just ci just validate-ontology
