name: normal
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: build
        run: just ci just lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: build
        run: just ci just build

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: build-docs

      - name: Commit generated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Update generated docs" || echo "No changes to commit"
          git push

      - name: Upload generated documentation as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: shacl-documentation
          path: docs/index.html

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: build
        run: just ci just test
